<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{88f0f169-9aec-448c-9545-39ea6c60d390}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	concrete				:ConcreteAssertions();
	tests					:CNM_AssertionInterfaceTests.AssertionTester(concrete);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN_IN_SEQUENCE();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>