<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="udfhgdshfksfkjshdkjfdhsfsdfsdfsfsdfsdfsdsdf" Id="{5933dbdd-385d-40f4-9103-aac4038dca7a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION udfhgdshfksfkjshdkjfdhsfsdfsdfsfsdfsdfsdsdf : sdfdsfsdfsd
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="udfhgdshfksfkjshdkjfdhsfsdfsdfsfsdfsdfsdsdf">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>